#!/usr/bin/env bash
# shellcheck shell=bash
set -euxo pipefail

# Get the current package.json version before any modifications
cur_pkg_version="$(jq -r .version package.json)"

# Get the latest GitHub release version (empty before the first release)
latest_release="$(gh release view --json tagName --jq .tagName 2>/dev/null || echo "")"
latest_release_version="${latest_release#v}"

# A package.json version that is ahead of the latest release has a release PR
# that was merged: release.yml creates the release, so there is nothing to do.
if [ -n "$latest_release_version" ] && [ "$cur_pkg_version" != "$latest_release_version" ]; then
	echo "Package version v$cur_pkg_version is newer than latest release $latest_release."
	echo "Release will be created by the release.yml workflow when the PR is merged."
	exit 0
fi

# Otherwise the package is at its latest release (or has none yet): open or
# update a PR for the unreleased changes.

# Get the latest released version tag
latest_tag="$(git tag --list | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+(-rc\.[0-9]+)?$' | sort -V | tail -1 || true)"

# Check if there are commits since the last release
if [ -n "$latest_tag" ]; then
	commits_since_release="$(git rev-list "$latest_tag"..HEAD --count)"
	if [ "$commits_since_release" -eq 0 ]; then
		echo "No commits since last release $latest_tag"
		exit 0
	fi
	echo "Found $commits_since_release commits since $latest_tag"
fi

# Get the next version from git-cliff
version="$(git cliff --bumped-version)"

# If git-cliff couldn't bump the version (e.g. only chore/deps commits since
# the last release), there's nothing to release. Bailing here avoids a later
# `npm version <same>` failure ("Version not changed").
if { [ -n "$latest_tag" ] && [ "$version" = "$latest_tag" ]; } || [ "${version#v}" = "$cur_pkg_version" ]; then
	echo "No version bump from commits since ${latest_tag:-the start}; nothing to release."
	exit 0
fi

# Get the changelog from git-cliff
changelog="$(git cliff --bump --unreleased | tail -n +2)"

if [ "${DRY_RUN:-1}" == 1 ]; then
	echo "version: $version"
	echo "changelog: $changelog"
	exit 0
fi

# Check if there are any unreleased changes
if [ -z "$changelog" ] || [ "$changelog" = "<!-- generated by git-cliff -->" ]; then
	echo "No unreleased changes found"
	exit 0
fi

# Configure git for automated commits
git config user.name mise-en-dev
git config user.email 123107610+mise-en-dev@users.noreply.github.com

# Configure git to use gh's credential helper. The checkout step uses
# persist-credentials: false (per zizmor's artipacked audit), so the
# token isn't written to .git/config and raw `git push` would 403.
gh auth setup-git

# Bump package.json; the "version" script writes CHANGELOG.md
npm version "${version#v}" --no-git-tag-version

git add package.json
git status

# Create release branch and commit
git checkout -B release
git commit -m "chore: release $version"

# Push to release branch
git push origin release --force

# Create or update PR
if gh pr create --title "chore: release $version" --body "$changelog" --label "release"; then
	echo "Created new release PR"
else
	gh pr edit --title "chore: release $version" --body "$changelog"
	echo "Updated existing release PR"
fi
