name: publish

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write # npm trusted publishing and provenance

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
      - run: mise run test
      - run: npm publish
